### PR TITLE
25 homepage news aggregator

### PR DESCRIPTION
**Pull request by benlk**
## Changes

Note that merging this PR effectively merges #25, because styles in here build off of styles in those commits.

This pull request makes the following changes:

- emboldens, centers and embiggens the widget titles in the homepage bottom area
- applies styles to the Link Roundups widget.

Screen Shot 2019-08-02 at 20 55 35

Collapses down to, at its smallest,
Screen Shot 2019-08-02 at 20 55 22

Below 700px, it's two-column: 

Screen Shot 2019-08-02 at 20 55 28

## Why

For #16

## Testing/Questions

Features that this PR affects:

- homepage

Questions that need to be answered before merging:

- [ ] is there any better way this could have been styled, than just kinda randomly floating things? Could CSS Grid have solved this problem?
- [ ] the widget only adds thumbnail-sized images. How hard do we want to try to get images of a different aspect ratio?
- [ ] make headline text bigger/smaller?

Steps to test this PR:

1. Install `link-roundups` plugin
2. create n>4 saved links with thumbnails
2. add to the Homepage Bottom widget area a Saved Links widget set to `4`, with thumbnail, no readmore, no excerpt

### CODE REVIEW

**Comment by benlk** [comment]
1h11m used of 2h

**Comment by joshdarby** [comment]
>  make headline text bigger/smaller?

I think it's ok since it matches what's in the mockup.

> the widget only adds thumbnail-sized images. How hard do we want to try to get images of a different aspect ratio?

I would think it'd be preferable to show bigger images, but I'll leave that up to @MirandaEcho.

Other than that, it looks good and works well.

**Comment by MirandaEcho** [comment]
@joshdarby - between development and review, how much time has been logged for this task, and what would it take to resize the images?

@kaylima - from a design perspective, what are your thoughts on thumbnail vs. wider images?

**Comment by joshdarby** [comment]
@MirandaEcho I've put in 30 minutes of review time and it looks like @benlk has spent 1 hr 11 minutes. So total of 1 hr 40ish minutes have been used so far.

**Comment by benlk** [comment]
@MirandaEcho resizing the images would require, at minimum:

- Copying the Link Roundups widget code over from that plugin, and modifying it so it doesn't conflict with that plugin's widget code
- Modifying the widget to output a wider image
- Check styles

I think that's about an hour's work.

**Comment by MirandaEcho** [comment]
Ok, given remaining time lets not do that for now, unless requested by the client or @kaylima from a design perspective.

**Comment by kaylima** [comment]
image

@benlk how long would it take to center the text under the images, but keep them the thumbnails the same size? (looking for a workaround to the image size issue)

also,  please decrease the space between the title and the organization (i.e. bring "ProPublica" up closer to the title)

and, can we cap the title length to keep it more streamlined? 2 lines perhaps plus a "..."?

**Comment by kaylima** [comment]
Let's leave the thumbnails as-is for now, but please do the following:

decrease the space between the title and the organization (i.e. bring "ProPublica" up closer to the title)

Q: can we cap the title length to keep it more streamlined? 2 lines perhaps plus a "..."?

**Comment by benlk** [comment]
Truncation or abbreviation of the headlines is something better done by Workday Minnesota with editorial judgement involved, rather than a plain "cut it off after `n` characters" rule.

If we wanted to do truncation based on the number of lines, because the line length is variable at different screen sizes, we'd still see wrapping without a frontend JS solution to enforce truncation at a specific number of lines.

But beyond that, truncation is bad like homepage carousels are bad.

**Comment by kaylima** [comment]
@benlk this is different because it's an aggregator and not their articles.

But, for sake of time, please just decrease the space between the title and the organization (i.e. bring "ProPublica" up closer to the title) and get on staging. thanks.

**Pull request merged**
