### PR TITLE
Sticky nav updates

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Increased left/right padding of nav items to 20px
- Added `text-transform: uppercase` attribute

Screen Shot 2019-08-08 at 10 12 15 AM

## Why

For #43

## Testing/Questions

Features that this PR affects:

- Sticky nav

Questions that need to be answered before merging:

- [ ] Does it look and function ok?

Steps to test this PR:

1. View the sticky nav on mobile and desktop

### CODE REVIEW

**Comment by kaylima** [comment]
@joshdarby looks good, but because this is the old logo, it's hard to tell if it will be big enough for the new one. here it is:

http://workdayminnesota.flywheelsites.com/wp-content/uploads/2019/08/workday-logo-color-rgb-336x153.png

**Comment by joshdarby** [comment]
@kaylima Here's how it looks with the new one. Should I increase the height? 

Screen Shot 2019-08-08 at 12 18 09 PM

**Comment by kaylima** [comment]
@joshdarby yes, let's bump it up to 45px for the height. thanks!

**Comment by joshdarby** [comment]
@kaylima Here it is at 45px.

Screen Shot 2019-08-08 at 12 22 15 PM

**Pull request merged**
