### PR TITLE
Design qa header

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Increased header width to 100% so donate and search icons are right by the screen edges
- Updated donate and search font to use @font-headline
- Increased menu link font size and decreased font weight
- Decreased height of menu area and increase height of top header
- Reduced size of donate and search left/right border and swapped color to @darkgray

Screen Shot 2019-08-07 at 6 08 58 PM

## Why

For #33 

## Testing/Questions

Features that this PR affects:

- Header and main nav

Questions that need to be answered before merging:

- [ ] Does it look ok now?
- [ ] Any other updates we should make?

Steps to test this PR:

1. View the header on any page

### CODE REVIEW

**Comment by kaylima** [comment]
> Looks like we still need more height for the header. Should be at least 134px (currently 120px).
> 
> We also may need even more, because we're doing a bigger logo... getting the specific height from Andrew.

@joshdarby:

> the height of the logo is 161px. The height of the nav bar is 212px.

**Comment by joshdarby** [comment]
> The height of the logo is 161px.
The height of the nav bar is 212px

@kaylima Does that mean we want to increase the logo to 161px and the header area to 212px? 

It looks a little too big like that
Screen Shot 2019-08-08 at 8 55 33 AM

**Comment by kaylima** [comment]
> > The height of the logo is 161px.
> > The height of the nav bar is 212px
> 
> @kaylima Does that mean we want to increase the logo to 161px and the header area to 212px?
> 
> It looks a little too big like that
> Screen Shot 2019-08-08 at 8 55 33 AM

Hmm... you're right @joshdarby. Here's what it should look like:
Screen Shot 2019-08-08 at 8 15 46 AM

And the logo we're using (already uploaded to the staging site)
workday-logo_tagline-reverse-rgb

Open to your thoughts on how to achieve this.

**Comment by kaylima** [comment]
P.S. you can see the logo on the staging site here: http://workdayminnesota.flywheelsites.com/

**Comment by joshdarby** [comment]
@kaylima how does this look? Logo is 120px and header container is 150px

Screen Shot 2019-08-08 at 11 01 03 AM

**Comment by kaylima** [comment]
@josh it needs just a little more space at the top and bottom, if you want to screenshare that might be faster. thanks!

**Pull request merged**
