### PR TITLE
9 fonts and pull quotes

### PR DESCRIPTION
**Pull request by benlk**
## Changes

This pull request makes the following changes:

- adds fonts, for #7 
- updates colors in stylesheet to match the values given in the mockup linked in #7
- adds those colors as the pre-selected colors in the Gutenberg color chooser
- pull quote styles for #9
    - different styles for the "solid color background" and "standard" style variants of Gutenberg blocks
    - orange "" for the solid background, padding so that it can have colored backgrounds with the black borders inside the background
    - green "" for the plain background, no padding
    -  10% outwards margin offset for alignleft, alignright.

Screen Shot 2019-07-31 at 20 20 58
Screen Shot 2019-07-31 at 20 14 46
Screen Shot 2019-07-31 at 17 13 07

## Testing/Questions

Features that this PR affects:

- the pull quote block, in all varieties
- Gutenberg color picker
- fonts across the site

Questions that need to be answered before merging:

- [x] fonts look okay?
- [x] blocks look okay?
- [ ] mockup didn't have a style for quote citations; should those be styled differently from the paragraphs in the quote?

Steps to test this PR:

1. create left/right/none/center/wide blocks, in the "Default" and "Solid Color" style variants
2. view at different sizes

### CODE REVIEW

**Comment by benlk** [comment]
Does this need to apply the frontend styles inside the editor for the colors used for the pull quote?

**Comment by joshdarby** [comment]
> Does this need to apply the frontend styles inside the editor for the colors used for the pull quote?

@benlk Up to you but it seems like it might be more trouble than it's worth. I'd ask for @MirandaEcho's input.

**Comment by joshdarby** [comment]
I know it's designed this way, but should we actually left-align the pull quote text instead of centering it? I know Gutenberg center aligns the text by default. It looks kind of weird when it's full or wide width with not a lot of text.

Screen Shot 2019-08-01 at 4 09 38 PM

**Comment by MirandaEcho** [comment]
@benlk - lets not worry about the styles within the editor
@joshdarby - Can we align it to (or just slightly beyond) the body text width, or is that difficult/time consuming?

**Comment by joshdarby** [comment]
One more thing I noticed is that when it's right aligned and you're at <980px, the pull quote extends ever so slightly out of the page container, allowing you to scroll to the right by like 1 or 2px. Here's a screenshot but it's next to impossible to see what I'm talking about in it since the comment background is white

Screen Shot 2019-08-01 at 4 18 21 PM

**Comment by joshdarby** [comment]
> @joshdarby - Can we align it to (or just slightly beyond) the body text width, or is that difficult/time consuming?

I'll defer to @benlk on that one but if I understand correctly, that would probably be time consuming to get perfect.

**Comment by MirandaEcho** [comment]
@kaylima can I get your thoughts on this, from a design perspective? Thanks!

**Comment by benlk** [comment]
If it's over by just a little, we can change the 10% bump-out to a lesser amount on smaller viewports, or use vw units rather than % of the container.

Making the unaligned pullquote block left-aligned makes sense, I'll make that change, depending on @MirandaEcho's answer to this question:

@MirandaEcho would it make sense to ask the client whether they want their text left/right/centered when the block is left/right/center or wide/full-width, or should we make that decision for them?

**Comment by benlk** [comment]
Updated left- and right-align styles, using pesticide.io to show borders of elements in Firefox's responsive viewer:

Screen Shot 2019-08-01 at 17 38 02
Screen Shot 2019-08-01 at 17 36 31
Screen Shot 2019-08-01 at 17 36 48
Screen Shot 2019-08-01 at 17 37 03
Screen Shot 2019-08-01 at 17 37 11

**Pull request merged**
