### PR TITLE
Style bylines at the end of articles

### PR DESCRIPTION
**Pull request by joshdarby**
## Changes

This pull request makes the following changes:

- Styles the bylines at the end of articles

Screen Shot 2019-08-13 at 4 12 15 PM

## Why

For #66

## Testing/Questions

Features that this PR affects:

- Bylines at the end of articles

Questions that need to be answered before merging:

- [ ] Does it look ok?

Steps to test this PR:

1. View a post with and see the byline after the content

### CODE REVIEW

**Comment by kaylima** [comment]
@josh I can't tell for sure, but it looks like the line between the name and date might be darker than the font/text... is that true? if so, let's make it match in the same grey color. then, good to go! thanks! should be `#ACACAC`

**Comment by joshdarby** [comment]
@kaylima The line is the same color as the name and date. They are all using the `darkgray` LESS variable which is #534B47. 

For reference: 
https://xd.adobe.com/spec/e12ba5e6-9fe1-448a-68e4-e701056351e0-971a/screen/b31b36e7-9b99-4a04-b37a-572cb5815bf0/Article-Revised/

**Comment by kaylima** [comment]
Screen Shot 2019-08-13 at 3 10 33 PM

¯\_(ツ)_/¯ either is fine. thanks!

**Comment by joshdarby** [comment]
@kaylima is this one good to go?

**Pull request merged**
